on:
  push:
    branches:
    - ana
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install libxml2-utils
    - run: xmllint --noout --schema mevzuat.xsd 5199.xml
